Computer Science 470-001(4738) and 570-001(7550) at Northern Arizona
University, Spring 2021

Topic: Artificial Intelligence.

Dates: 01/11/2021 - 05/07/2021.

Meeting time/place: MoWeFr 9:10AM - 10:00AM, SBS West, Rm 109 .

Syllabus: TODO

** Textbook

The required readings will be from [[http://aima.cs.berkeley.edu/][Artificial Intelligence: A Modern
Approach]] by Russell and Norvig.
- [[https://arizona-nau-primo.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=01NAU_ALMA21108980210003842&context=L&vid=01NAU&lang=en_US&search_scope=Everything&adaptor=Local%2520Search%2520Engine&tab=default_tab&query=any,contains,artificial%2520intelligence%2520a%2520modern%2520approach&mode=Basic][Dead tree book at Cline]]

** Screencasts

To learn basic R programming skills which will be highly relevant to
your coding projects in this class, please watch [[https://www.youtube.com/playlist?list=PLwc48KSH3D1M78ilQi35KPe2GHa7B_Rme][these screencasts]] and
follow along (pause the videos, type the code, then and execute the
code on your own computer).

** Lectures

TODO

** Homeworks

TODO

** How to ace this class

Before class you should read the suggested book chapters. When you
read, write a summary in your own words of every paragraph or
section. Also write questions that you have during your reading so you
can ask in class (if related to the lecture topic) or in office hours.

During class, instead of copying what I write on the whiteboard, I
would suggest to try to write what you understood in your own
words. Also I would suggest to ask questions in class as soon as you
need clarification.

After class, you should review your notes with one of your classmates
(ask one of the students who seem to be correctly answering a lot of
questions). Ask each other questions and try to teach/summarize some
of the material with each other -- that is one of the best ways to
learn.

Finally after doing all of the above, please drop by my office hours (Tuesdays and Wednesdays, 3-4pm, 90-210),
or email me to schedule a meeting.

